/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IPOGTLevelTransitionAnalyzerForm.java
 *
 * Created on Oct 28, 2011, 9:44:54 AM
 */

package FluoObjects;
import javax.swing.JViewport;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import utilities.CommonGuiMethods;

/**
 *
 * @author Taihao
 */
public class IPOGTLevelTransitionAnalyzerForm extends javax.swing.JFrame implements ActionListener{

    IPOGTLevelTransitionAnalyzer m_cAnalyzer;
    /** Creates new form IPOGTLevelTransitionAnalyzerForm */
    public IPOGTLevelTransitionAnalyzerForm(IPOGTLevelTransitionAnalyzer analyzer) {
        initComponents();
        m_cAnalyzer=analyzer;
        additionalInit();
        setVisible(true);
        CommonGuiMethods.makeClipboardCopiable(this);
    }
    void additionalInit(){
        m_cAnalyzer.addActionListener(this);
        m_cAnalyzer.setDisplayingForm(this);
        JViewport jvp=new JViewport();
        jvp.setView(m_cAnalyzer.getContentPane());
        IPOLevelSP.setViewport(jvp);
    }
    public void actionPerformed(ActionEvent ae){
        String commond=ae.getActionCommand();
        if(commond.startsWith("parentTitle")) setTitle(commond.substring(commond.indexOf("Level")));
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IPOLevelSP = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IPOLevelSP, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IPOLevelSP, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new IPOGTLevelTransitionAnalyzerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane IPOLevelSP;
    // End of variables declaration//GEN-END:variables

}
