/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MasterFittingGUI.java
 *
 * Created on Feb 16, 2012, 12:09:24 PM
 */

package utilities.Gui;
import utilities.Non_LinearFitting.ImageFittingGUI;
import utilities.Non_LinearFitting.CurveFittingGUI;
import javax.swing.JViewport;
import utilities.CommonGuiMethods;
import utilities.Gui.AnalysisMasterForm;

/**
 *
 * @author Taihao
 */
public class MasterFittingGUI extends javax.swing.JFrame {

    /** Creates new form MasterFittingGUI */
    static ImageFittingGUI m_cImageFitter;
    static CurveFittingGUI m_cCurveFitter;
    static AnalysisMasterForm m_cMasterForm;
    public MasterFittingGUI() {
        initComponents();
        completeGUI();
        CommonGuiMethods.makeClipboardCopiable(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MasterTabbedPane = new javax.swing.JTabbedPane();
        ImageFittingPane = new javax.swing.JScrollPane();
        CurveFittingPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MasterTabbedPane.addTab("Image Fitting", ImageFittingPane);
        MasterTabbedPane.addTab("Curve Fitting", CurveFittingPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MasterTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MasterTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterFittingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane CurveFittingPane;
    private javax.swing.JScrollPane ImageFittingPane;
    private javax.swing.JTabbedPane MasterTabbedPane;
    // End of variables declaration//GEN-END:variables
    void completeGUI(){
        m_cImageFitter=new ImageFittingGUI();
        m_cCurveFitter=new CurveFittingGUI();

        JViewport ImageView=new JViewport();
        ImageView.setView(m_cImageFitter.getContentPane());
        ImageFittingPane.setViewport(ImageView);

        JViewport CurveView=new JViewport();
        CurveView.setView(m_cCurveFitter.getContentPane());
        CurveFittingPane.setViewport(CurveView);
    }
    public void setMasterForm(AnalysisMasterForm cMasterForm){
        m_cMasterForm=cMasterForm;
        m_cImageFitter.setMasterForm(cMasterForm);
        m_cCurveFitter.setMasterForm(cMasterForm);
    }
    public ImageFittingGUI getImageFitter(){
        return m_cImageFitter;
    }
    public static void closeAllTempWindows(){
        m_cImageFitter.closeFittingImages();
        PlotHandlerGui.closeAllPlotWindowPlus();
        AnalysisMasterForm.closeAllTempImages();
    }
}
