/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package utilities.AbfHandler;
import utilities.io.FileAssist;
import utilities.io.PrintAssist;

/**
 *
 * @author Taihao
 */
public class AbfAnalysisGui extends javax.swing.JFrame {

    /**
     * Creates new form AbfAnalysisGui
     */
    public AbfAnalysisGui() {
        initComponents();
    }
    Abf m_cAbf;
    AbfHandler m_cHandler;
    int importAbf(){
        if(m_cAbf==null) m_cAbf=new Abf();
//        String path=FileAssist.getFilePath("import an abf file", "D:\\Taihao\\EPData\\G4ST\\S176P\\S-C", "Abf or Dat file", "Abf,Dat", true);
        String path=FileAssist.getFilePath("import an abf file", "D:\\Taihao\\Electrophysiology Data\\Wei Zhang", "abf,dat or atf file", "abf,dat,atf", true);
        if(path==null) return -1;
        if(FileAssist.getFileExtention(path).equalsIgnoreCase("atf")) {
            importAtf(path);
            m_cAbf.showData();
            return 1;
        }
        m_cAbf.importData(path);
        m_cAbf.showData();
        m_cHandler=new AbfHandler(m_cAbf);
        return 1;
    }
    int importAtf(String path){
        if(m_cAbf==null) m_cAbf=new Abf();
        return m_cAbf.importAtf(path);
    }
    void exportAbf(){
        String path=FileAssist.getFilePath("export an abf file", "D:\\Taihao\\EPData\\G4ST\\S176P\\S-C", "Dat file", "Dat", false);
        m_cAbf.exportData(path);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        FileOptionCB = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        AbfProcessingOptionCB = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("File");

        FileOptionCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "import", "export" }));
        FileOptionCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileOptionCBActionPerformed(evt);
            }
        });

        jLabel2.setText("Process");

        AbfProcessingOptionCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "multiply", "squarePulse" }));
        AbfProcessingOptionCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbfProcessingOptionCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FileOptionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AbfProcessingOptionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(FileOptionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(AbfProcessingOptionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(269, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FileOptionCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileOptionCBActionPerformed
        // TODO add your handling code here:
        String option=(String)FileOptionCB.getSelectedItem();
        if(option.contentEquals("import"))
            importAbf();
        if(option.contentEquals("export"))
            exportAbf();
    }//GEN-LAST:event_FileOptionCBActionPerformed

    private void AbfProcessingOptionCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbfProcessingOptionCBActionPerformed
        // TODO add your handling code here:
        String option=(String) AbfProcessingOptionCB.getSelectedItem();
        if(option.contentEquals("multiply")){
            m_cHandler.multiplyChannels(3);
        }
        if(option.contentEquals("squarePulse")){
            m_cHandler.squarePulses(0,100,200);
        }
        m_cAbf.showData();
    }//GEN-LAST:event_AbfProcessingOptionCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbfAnalysisGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbfAnalysisGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbfAnalysisGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbfAnalysisGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AbfAnalysisGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AbfProcessingOptionCB;
    private javax.swing.JComboBox FileOptionCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
